version: '3.8'

services:
  # Node.js Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-backend
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  # React Frontend Service (with Apache on port 80)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "9090:80"  # Serving on standard HTTP port
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

# Custom network for inter-container communication
networks:
  app-network:
    driver: bridge
