version: '3.8'

services:
  backend:
    image: azuresubha/node-backend:latest
    container_name: node-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: azuresubha/react-frontend:latest
    container_name: react-frontend
    ports:
      - "9090:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
