version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-backend
    ports:
      - "5000:5000"  # Add this line to expose backend port
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0  # Add this for Node.js to listen on all interfaces
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "9090:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
